language: java
jdk: oraclejdk8
services:
- docker
script:
- "./gradlew check --info"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    - SPRING_PROFILES_ACTIVE=default,integration-tests
branches:
  only:
  - master
notifications:
  slack:
    secure: qv9PEK9fWuKJpeTabAvgMM1/I7NO2IsexfpYVNh/ZfbikOku5xAU6KJoepYOByB2Xd5/aLGM8NXmEt5LH19LHSKzNeb5JqoFU2OCkXV93U5WXPV175isUzABfJC7N/ZKb2m9tWc6Rjp+WEEBH736WgrqMGdmELO2VEcEOukSa+IszOGhn5RhQLMLuzrkW2JdmWBVnIHStotGa7By+hxEqRgUNhVaiHj1y7fDtctPjfGklMbETOy6CuqRT7DeGwi0u6PWZs3mIuRzRVfsw/3nuU1axA8+sSEd2z0i8c3nELtZ1RH7Si+D9aQ7TEkVNJFcE2zcpMAi+5QKxoO4xu/RR7XNpIXHZfGl3kotbLtZGkL/kpTs1g6eZAlwOX0WtgyXnnRvH3YxE9ROGaTin9bWBMarFxavHJbMO8qwXrXLRafEPT437GxcNL7UaAdCM/ELRnelDIhnbC1fmeSkHfN9W1wdHWyi8xuaANJtsXVPPmBYDmByU5l7hsLwgyiv7fUDGNfxSXJf7QOZKLEKTYEpea3F6fbWzyKCv6S0MJWM7v7o/pG4T82DKCXWWOfQppFnwe0fNYJmXWGgT1/hmTZzhiPeGm0O83AA6gP5vT+k1zKxKXvvjI6Ohh5aA2BpESkxEhGGCvkzLCeQXo3VeSu4SOgMaPYT/TGc9Emnd4CQjbo=
